version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "9001:8080"  # Expose to your internal network
    volumes:
      - ./searxng-data:/etc/searxng
    environment:
      - SEARXNG_HOSTNAME=0.0.0.0
      - SEARXNG_SECRET_KEY=your_random_secret_key_here  # Generate with `openssl rand -hex 32`
    networks:
      - searxng-net

  redis:
    image: redis:alpine
    container_name: searxng-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    networks:
      - searxng-net

networks:
  searxng-net:
